services:
  api:
    build: .
    container_name: adocao-api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/adocao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: adocao-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adocao
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: